### ISSUE TITLE
Certificate verify failed.

### ISSUE THREAD

**Issue by avwifiguy** [CodeCorrupt/godaddy-dyndns#2]
Hi,

Everything worked fine with this and the Sascha's script but at the end  both places I got this exception.
2017-02-04 20:36:17,728 Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
Any hints if I am doing something wrong or script needs any enhancements?

Thanks

**Comment by CodeCorrupt** [comment]
Hey, I'm sorry I haven't been using this script myself lately. Last I heard GoDaddy updated their interface so I believe the issue lies in the PyGodaddy module that I had forked and patched when I first made this. 

I'd recommend looking there but unfortunately I'm not supporting this script anymore until I have a need for it again. Please submit a pull request though if you end up patching.

Thanks
